# GNOME Customization
# Use gsettings list-schemas and gsettings list-recursively to get all possible settings
- name: Show battery percentage
  community.general.dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"
    state: present

- name: Change clock format to 12h
  community.general.dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'12h'"
    state: present

- name: Enable tap to click on touchpad
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: "true"
    state: present

- name: Disable natural scroll
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "false"
    state: present

- name: Disable auto brightness
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/power/ambient-enabled"
    value: "false"
    state: present

- name: Enable Night Light
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
    value: "true"
    state: present

- name: Set Night Light color temperature
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-temperature"
    value: "uint32 1730"
    state: present

- name: Set Favorite Apps
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['firefox.desktop', 'org.gnome.Terminal.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Software.desktop']"
    state: present

- name: Set Caps Lock to Escape
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['caps:swapescape']"
    state: present
